### ISSUE TITLE
Create Nuget package

### ISSUE THREAD

**Issue by ochsec** [sagifogel/Ramda.NET#2]
Are you willing to create a Nuget package to make cloud builds easier?

**Comment by sagifogel** [comment]
of course

**Comment by sagifogel** [comment]
Done - [https://www.nuget.org/packages/Ramda.NET/1.0.0](https://www.nuget.org/packages/Ramda.NET/1.0.0)

**Comment by ochsec** [comment]
Thanks, I'll try it out
